[build]
target = [
  "xtensa-esp32-none-elf", 
  "xtensa-esp32s2-none-elf", 
  "xtensa-esp32s3-none-elf", 
  "riscv32imc-unknown-none-elf", 
  "riscv32imac-unknown-none-elf"
]

[unstable]
build-std = ["alloc", "core"]
